#ifndef __com_sun_star_ucb_RestRequestParameter_idl__
#define __com_sun_star_ucb_RestRequestParameter_idl__

#include <com/sun/star/ucb/RestRequestEnumerator.idl>

module com { module sun { module star { module ucb {

struct RestRequestParameter
{

    string Name;
    string Method;
    string Url;
    string Header;
    string Query;
    string Data;
    string Json;
    string Optional;
    com::sun::star::ucb::RestRequestEnumerator Enumerator;
    boolean NoAuth;
    boolean NoRedirect;

};

}; }; }; };

#endif
