#ifndef __com_sun_star_ucb_RestRequestTokenType_idl__
#define __com_sun_star_ucb_RestRequestTokenType_idl__

module com { module sun { module star { module ucb {

constants RestRequestTokenType
{

    const long TOKEN_NONE = 0;
    const long TOKEN_URL = 1;
    const long TOKEN_REDIRECT = 2;
    const long TOKEN_QUERY = 4;
    const long TOKEN_JSON = 8;

};

}; }; }; };

#endif
