#ifndef __com_sun_star_ucb_XRestDataSource_idl__
#define __com_sun_star_ucb_XRestDataSource_idl__

#include <com/sun/star/uno/XInterface.idl>
#include <com/sun/star/ucb/XRestProvider.idl>
#include <com/sun/star/auth/XRestKeyMap.idl>
#include <com/sun/star/sdbc/XConnection.idl>
#include <com/sun/star/sdbc/XStatement.idl>
#include <com/sun/star/beans/Optional.idl>

module com { module sun { module star { module ucb {

interface XRestDataSource: com::sun::star::uno::XInterface
{

    boolean shutdownConnection([in] boolean Compact);
    ::com::sun::star::uno::XInterface getUser([in] string Name);
    ::com::sun::star::auth::XRestKeyMap initializeUser([in] string Name,
                                                       [out] string Error);
    boolean isIdentifier([in] string UserId,
                         [in] string ItemId);
    ::com::sun::star::auth::XRestKeyMap getItem([in] ::com::sun::star::auth::XRestKeyMap User,
                                             [in] ::com::sun::star::auth::XRestKeyMap Identifier);
    ::com::sun::star::sdbc::XStatement getFolderContent([in] ::com::sun::star::auth::XRestKeyMap User,
                                                        [in] ::com::sun::star::auth::XRestKeyMap Identifier,
                                                        [in] ::com::sun::star::auth::XRestKeyMap Content,
                                                        [out] boolean Updated);
    boolean insertNewDocument([in] string UserId,
                              [in] string ItemId,
                              [in] string ParentId,
                              [in] ::com::sun::star::auth::XRestKeyMap Content);
    boolean insertNewFolder([in] string UserId,
                            [in] string ItemId,
                            [in] string ParentId,
                            [in] ::com::sun::star::auth::XRestKeyMap Content);
    string updateSync([in] string UserId,
                      [in] string ItemId,
                      [in] short Mode);
    short updateLoaded([in] string UserId,
                       [in] string ItemId,
                       [in] short Value,
                       [in] short Default);
    string updateTitle([in] string UserId,
                       [in] string ItemId,
                       [in] string Value,
                       [in] string Default);
    long updateSize([in] string UserId,
                    [in] string ItemId,
                    [in] long Size);
    boolean updateTrashed([in] string UserId,
                          [in] string ItemId,
                          [in] boolean Value,
                          [in] boolean Default);
    any synchronize([in] ::com::sun::star::auth::XRestKeyMap User,
                    [in] any Value);
    void callBack([in] ::com::sun::star::auth::XRestKeyMap Item,
                  [in] ::com::sun::star::beans::Optional<::com::sun::star::auth::XRestKeyMap> Response);
    boolean isChildId([in] string UserId,
                      [in] string ParentId,
                      [in] string ItemId);
    string selectChildId([in] string UserId,
                         [in] string ParentId,
                         [in] string Title);
    long countChildTitle([in] string UserId,
                         [in] string ParentId,
                         [in] string Title);
    void checkNewIdentifier([in] ::com::sun::star::auth::XRestKeyMap User);
    string getNewIdentifier([in] ::com::sun::star::auth::XRestKeyMap User);

    [attribute, readonly] ::com::sun::star::sdbc::XConnection Connection;
    [attribute, readonly] ::com::sun::star::ucb::XRestProvider Provider;
    [attribute, readonly] string Url;
    [attribute, readonly] boolean IsValid;
    [attribute, readonly] string Error;

};

}; }; }; };

#endif
