#ifndef __com_sun_star_ucb_XRestRequest_idl__
#define __com_sun_star_ucb_XRestRequest_idl__

#include <com/sun/star/uno/XInterface.idl>
#include <com/sun/star/ucb/RestRequestParameter.idl>
#include <com/sun/star/ucb/XRestKeyMap.idl>
#include <com/sun/star/beans/Optional.idl>
#include <com/sun/star/io/XInputStream.idl>
#include <com/sun/star/io/XOutputStream.idl>
#include <com/sun/star/container/XEnumeration.idl>


module com { module sun { module star { module ucb {

interface XRestRequest: com::sun::star::uno::XInterface
{

    void initializeSession([in] string Scheme,
                           [in] string Name);
    short getSessionMode([in] string Host);
    com::sun::star::beans::Optional<com::sun::star::ucb::XRestKeyMap> execute([in] com::sun::star::ucb::RestRequestParameter Parameter);
    com::sun::star::container::XEnumeration getEnumerator([in] com::sun::star::ucb::RestRequestParameter Parameter);
    com::sun::star::io::XInputStream getInputStream([in] com::sun::star::ucb::RestRequestParameter Parameter,
                                                    [in] long Chunk,
                                                    [in] long Buffer);
    com::sun::star::io::XOutputStream getOutputStream([in] com::sun::star::ucb::RestRequestParameter Parameter,
                                                      [in] long Size,
                                                      [in] long Chunk,
                                                      [out] com::sun::star::beans::Optional<com::sun::star::ucb::XRestKeyMap> Response);

    [attribute, readonly] any Session;
    [attribute, readonly] string Error;
    [attribute, readonly] boolean IsValid;

};

}; }; }; };

#endif
